apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: voting
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: voting
    spec:
      containers:
        - name: worker-app
          image: pavany77/worker:v1